sonata_admin:
    title: 'Hospital Reviews Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    security:
        handler: sonata.admin.security.handler.noop
    options:
        html5_validate: false